# Generated by Django 2.2.5 on 2019-09-19 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('rated', models.CharField(max_length=10, verbose_name='Rated')),
                ('released', models.CharField(max_length=15, verbose_name='Released')),
                ('runtime', models.CharField(max_length=10, verbose_name='Runtime')),
                ('genre', models.CharField(max_length=50, verbose_name='Genre')),
                ('director', models.CharField(max_length=20, verbose_name='Director')),
                ('writer', models.TextField(verbose_name='Writer')),
                ('actors', models.TextField(verbose_name='Actors')),
                ('plot', models.TextField(verbose_name='Plot')),
                ('language', models.CharField(max_length=15, verbose_name='Language')),
                ('country', models.CharField(max_length=20, verbose_name='Country')),
                ('awards', models.TextField(verbose_name='Awards')),
                ('ratings', models.TextField(verbose_name='Ratings')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movies')),
            ],
            options={
                'ordering': ('movie',),
            },
        ),
    ]
