# Generated by Django 2.2.5 on 2019-09-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='actors',
            field=models.TextField(blank=True, verbose_name='Actors'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='awards',
            field=models.TextField(blank=True, verbose_name='Awards'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='country',
            field=models.CharField(blank=True, max_length=20, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(blank=True, max_length=20, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.CharField(blank=True, max_length=50, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='language',
            field=models.CharField(blank=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='plot',
            field=models.TextField(blank=True, verbose_name='Plot'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='rated',
            field=models.CharField(blank=True, max_length=10, verbose_name='Rated'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='ratings',
            field=models.TextField(blank=True, verbose_name='Ratings'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='released',
            field=models.CharField(blank=True, max_length=15, verbose_name='Released'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='runtime',
            field=models.CharField(blank=True, max_length=10, verbose_name='Runtime'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='writer',
            field=models.TextField(blank=True, verbose_name='Writer'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.IntegerField(blank=True, verbose_name='Year'),
        ),
    ]
