# Generated by Django 2.2.5 on 2019-09-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190919_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(blank=True, max_length=60, verbose_name='Title'),
        ),
    ]
