# Generated by Django 2.2.5 on 2019-09-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190919_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.CharField(blank=True, max_length=10, verbose_name='Year'),
        ),
    ]
