# Generated by Django 2.2.5 on 2019-09-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190919_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='actors',
            new_name='Actors',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='awards',
            new_name='Awards',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='director',
            new_name='Director',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='genre',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='language',
            new_name='Language',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='plot',
            new_name='Plot',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='rated',
            new_name='Rated',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='released',
            new_name='Released',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='runtime',
            new_name='Runtime',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='writer',
            new_name='Writer',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='year',
            new_name='Year',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='ratings',
        ),
        migrations.AddField(
            model_name='movies',
            name='Ratings',
            field=models.TextField(blank=True, verbose_name='Ratings'),
        ),
    ]
