# Generated by Django 2.2.5 on 2019-09-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20190919_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='Actors',
            new_name='actors',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='Awards',
            new_name='awards',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='Director',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='Language',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='Plot',
            new_name='plot',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='Rated',
            new_name='rated',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='Ratings',
            new_name='ratings',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='Runtime',
            new_name='runtime',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='Writer',
            new_name='writer',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='Year',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='Released',
        ),
        migrations.AddField(
            model_name='movies',
            name='released',
            field=models.CharField(blank=True, max_length=15, verbose_name='Released'),
        ),
    ]
