# Generated by Django 2.2.5 on 2019-09-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20190919_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='poster',
            field=models.TextField(blank=True, verbose_name='Poster'),
        ),
    ]
