# Generated by Django 2.2.5 on 2019-09-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movies_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='boxoffice',
            field=models.CharField(blank=True, max_length=20, verbose_name='BoxOffice'),
        ),
        migrations.AddField(
            model_name='movies',
            name='dvd',
            field=models.CharField(blank=True, max_length=15, verbose_name='DVD'),
        ),
        migrations.AddField(
            model_name='movies',
            name='imdbID',
            field=models.CharField(blank=True, max_length=20, verbose_name='imdbID'),
        ),
        migrations.AddField(
            model_name='movies',
            name='imdbRating',
            field=models.CharField(blank=True, max_length=10, verbose_name='imdbRating'),
        ),
        migrations.AddField(
            model_name='movies',
            name='imdbVotes',
            field=models.CharField(blank=True, max_length=10, verbose_name='imdbVotes'),
        ),
        migrations.AddField(
            model_name='movies',
            name='metascore',
            field=models.CharField(blank=True, max_length=10, verbose_name='Metascore'),
        ),
        migrations.AddField(
            model_name='movies',
            name='production',
            field=models.CharField(blank=True, max_length=30, verbose_name='Production'),
        ),
        migrations.AddField(
            model_name='movies',
            name='response',
            field=models.CharField(blank=True, max_length=20, verbose_name='Response'),
        ),
        migrations.AddField(
            model_name='movies',
            name='type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='movies',
            name='website',
            field=models.CharField(blank=True, max_length=20, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Title'),
        ),
    ]
