# Generated by Django 2.2.5 on 2019-09-19 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20190919_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='imdbID',
            new_name='imdbid',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='imdbRating',
            new_name='imdbrating',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='imdbVotes',
            new_name='imdbvotes',
        ),
    ]
