# Generated by Django 2.2.5 on 2019-09-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20190919_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='country',
            field=models.CharField(blank=True, max_length=40, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='imdbrating',
            field=models.CharField(blank=True, max_length=30, verbose_name='imdbRating'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='imdbvotes',
            field=models.CharField(blank=True, max_length=30, verbose_name='imdbVotes'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='language',
            field=models.CharField(blank=True, max_length=45, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='metascore',
            field=models.CharField(blank=True, max_length=30, verbose_name='Metascore'),
        ),
    ]
