# Generated by Django 2.2.5 on 2019-09-19 18:37

import django.contrib.postgres.fields
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20190919_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='ratings',
            field=django.contrib.postgres.fields.ArrayField(base_field=jsonfield.fields.JSONField(blank=True), size=None),
        ),
    ]
