# Generated by Django 2.2.5 on 2019-09-19 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20190919_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='ratings',
        ),
    ]
