# Generated by Django 2.2.5 on 2019-09-19 18:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_remove_movies_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='ratings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
