# Generated by Django 2.2.5 on 2019-09-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_movies_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='boxoffice',
            field=models.CharField(blank=True, max_length=50, verbose_name='BoxOffice'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='country',
            field=models.CharField(blank=True, max_length=60, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(blank=True, max_length=50, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='dvd',
            field=models.CharField(blank=True, max_length=45, verbose_name='DVD'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='imdbid',
            field=models.CharField(blank=True, max_length=40, verbose_name='imdbID'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='imdbrating',
            field=models.CharField(blank=True, max_length=50, verbose_name='imdbRating'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='imdbvotes',
            field=models.CharField(blank=True, max_length=50, verbose_name='imdbVotes'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='language',
            field=models.CharField(blank=True, max_length=60, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='metascore',
            field=models.CharField(blank=True, max_length=50, verbose_name='Metascore'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='production',
            field=models.CharField(blank=True, max_length=50, verbose_name='Production'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='response',
            field=models.CharField(blank=True, max_length=50, verbose_name='Response'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='runtime',
            field=models.CharField(blank=True, max_length=50, verbose_name='Runtime'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='type',
            field=models.CharField(blank=True, max_length=40, verbose_name='Type'),
        ),
    ]
