# Generated by Django 2.2.5 on 2019-09-20 05:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20190920_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='ratings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
